version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=1234567890.dkr.ecr.us-east-1.amazonaws.com/corp
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG is $IMAGE_TAG
      - docker run --rm -v `pwd`:/sln --workdir /sln microsoft/aspnetcore-build:2.0.5-2.1.4-jessie bash test.sh
  build:
    commands:
      - docker run --rm -v `pwd`:/sln --workdir /sln node:9.6.1 bash build_frontend.sh
      - docker run --rm -v `pwd`:/sln --workdir /sln microsoft/aspnetcore-build:2.0.5-2.1.4-jessie bash build.sh
      - cd src/Corp.Corp.Web.Mvc/
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - cd ../.. && pwd
      - printf '[{"name":"corp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - docker run -e DB_MIGRATION_CONNECTION_STRING=$DB_MIGRATION_CONNECTION_STRING --rm -v `pwd`:/sln --workdir /sln microsoft/aspnetcore-build:2.0.5-2.1.4-jessie bash migrate.sh
artifacts:
    files: imagedefinitions.json